language: go
sudo: false
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master
before_install:
  - go get github.com/mattn/goveralls
install:
  - go get -t ./...
script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test -v ./...